{% set name = "django-pygwalker" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-pygwalker-{{ version }}.tar.gz
  sha256: d4ce480b7a63faaae44729ad04cdc17575bffbcb6eb57789330ca24ade8fa938

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - python-build
    - setuptools >=67.7.2
    - setuptools-scm >=7.1
    - wheel >=0.40.0
    - pip
  run:
    - python >=3.8
    - django >=3.2,<5.0
    - django-handyhelpers >=0.3.10
    - pandas
    - pygwalker

test:
  imports:
    - djangoaddicts.pygwalker
  commands:
    - pip check
  requires:
    - pip

about:
  summary: PyGWalker views for Django projects
  home: https://github.com/djangoaddicts/django-pygwalker
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
